# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Classification and Identification of Urban Objects Using LiDAR Data
email: glb321@nyu.edu
description: >- # this means to ignore newlines until "baseurl:"
As LiDAR technology becomes cheaper and more readily accessible, point cloud data of urban areas in tandem becomes not only more abundant but also of higher fidelity and resolution. This data can be of great use to city officials and planners for many purposes, including the inventorying and cataloging of objects within the urban and built environments – objects such as buildings, street furniture, traffic lights, and lampposts. To accomplish this inventorying, data scientists can utilize state of the art as well as conventional machine and deep learning techniques for urban object detection, segmentation, and classification. There are, however, more than a multitude of methods – each with specific advantages and disadvantages. This project will compile a database of these methods and analyze which are most adept at the detection, segmentation, and classification of urban objects using metrics tailored for the purpose of urban inventorying.
baseurl: "capstone" # the subpath of your site, e.g. /blog
url: "https://github.com/gbarrett2/capstone.git" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plugins:
  - jekyll-redirect-from